"""empty message

Revision ID: e12cff07a3fa
Revises: 
Create Date: 2026-01-18 18:06:48.117011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e12cff07a3fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('id_telegram', sa.String(length=32), nullable=True),
    sa.Column('remember_token', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_id_telegram'), 'users', ['id_telegram'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('end_date >= start_date', name='trips_dates_chk'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'date', name='trip_days_trip_id_date_unique'),
    sa.UniqueConstraint('trip_id', 'day_number', name='trip_days_trip_id_day_number_unique')
    )
    op.create_table('trip_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('inviter_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'revoked', 'expired', name='invitation_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_trip_invitations_email'), 'trip_invitations', ['email'], unique=False)
    op.create_index('trip_invitations_unique_pending', 'trip_invitations', ['trip_id', 'email'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('trip_members',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('reader', 'editor', 'admin', name='trip_member_role'), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('trip_id', 'user_id')
    )
    op.create_index('trip_members_user_id_index', 'trip_members', ['user_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_day_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost_currency', sa.String(length=3), nullable=True),
    sa.Column('cost_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('booking_ref', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('ends_at IS NULL OR starts_at IS NULL OR ends_at >= starts_at', name='activities_time_range_chk'),
    sa.ForeignKeyConstraint(['trip_day_id'], ['trip_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('activities_trip_day_id_starts_at_index', 'activities', ['trip_day_id', 'starts_at'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attachable_type', sa.String(), nullable=False),
    sa.Column('attachable_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('trip_day_id', sa.UUID(), nullable=True),
    sa.Column('uploader_id', sa.BigInteger(), nullable=False),
    sa.Column('disk', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('mime', sa.String(length=127), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trip_day_id'], ['trip_days.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('attachments_trip_attachable_index', 'attachments', ['trip_id', 'attachable_type', 'attachable_id'], unique=False)
    op.create_table('hotel_stays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_day_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('checkin_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checkout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booking_ref', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trip_day_id'], ['trip_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('hotel_stays_trip_day_id_index', 'hotel_stays', ['trip_day_id'], unique=False)
    op.create_table('transport_legs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_day_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('flight', 'train', 'bus', 'car', 'boat', 'other', name='transport_kind'), nullable=False),
    sa.Column('carrier', sa.String(), nullable=True),
    sa.Column('ref_code', sa.String(), nullable=True),
    sa.Column('depart_place', sa.String(), nullable=False),
    sa.Column('arrive_place', sa.String(), nullable=False),
    sa.Column('depart_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrive_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trip_day_id'], ['trip_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('transport_legs_trip_day_id_depart_at_index', 'transport_legs', ['trip_day_id', 'depart_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('transport_legs_trip_day_id_depart_at_index', table_name='transport_legs')
    op.drop_table('transport_legs')
    op.drop_index('hotel_stays_trip_day_id_index', table_name='hotel_stays')
    op.drop_table('hotel_stays')
    op.drop_index('attachments_trip_attachable_index', table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('activities_trip_day_id_starts_at_index', table_name='activities')
    op.drop_table('activities')
    op.drop_index('trip_members_user_id_index', table_name='trip_members')
    op.drop_table('trip_members')
    op.drop_index('trip_invitations_unique_pending', table_name='trip_invitations', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_trip_invitations_email'), table_name='trip_invitations')
    op.drop_table('trip_invitations')
    op.drop_table('trip_days')
    op.drop_table('trips')
    op.drop_index(op.f('ix_users_id_telegram'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
